autoencoder:
  loss: mse
  latent_size: 48
  encoder:
    name: dcgan
    width: 64
  decoder:
    name: dcgan
    width: 64

data:
  name: celeba
  ratio_val: 0.00001
  image_size: 64

optim:
  batch_size: 250
  lr: 0.0001 
  weight_decay: 0
  num_steps: 100000
  val_freq: 1000
  val_iter: 10


flow:
  num_steps: 2000
  num_projs: 300 #250
  num_sub_projs: 220
  num_percentiles: 80000
  dt: 5
  reg: 0
  epsilon: 5
  delta: 0.000001
  val_freq: 100
  resample_thetas: True
  num_steps_resampling: 30
  sigma_noise: 0.000001









